spring.datasource.url=jdbc:postgresql://localhost:5432/spring_blog
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties (optional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#exception config
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false